- name: install vim
  pacman:
    name: neovim
    state: present
- name: Make github directory
  file:
    path: '/home/{{ user.name }}/github'
    state: directory
- name: Clone neovim config repo
  ansible.builtin.git:
    repo: 'https://github.com/fadyio/nvim.git'
    dest: '/home/{{ user.name }}/github/nvim'
- name: Create symbolic link for neovim config
  ansible.builtin.file:
    src: '/home/{{ user.name }}/github/nvim'
    dest: '/home/{{ user.name }}/.config/nvim'
    state: link
- name: Install vscode extensions
  ansible.builtin.command: 'code --install-extension {{ item }}'
  become_user: '{{ user.name }}'
  register: ext_install
  changed_when: ext_install.rc != 0
  loop:
    - amazonwebservices.aws-toolkit-vscode
    - astro-build.astro-vscode
    - bradlc.vscode-tailwindcss
    - catppuccin.catppuccin-vsc
    - github.copilot
    - github.copilot-chat
    - github.remotehub
    - github.vscode-github-actions
    - github.vscode-pull-request-github
    - golang.go
    - hashicorp.hcl
    - hashicorp.terraform
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - ms-python.debugpy
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-vscode-remote.remote-containers
    - ms-vscode-remote.remote-ssh
    - ms-vscode-remote.remote-ssh-edit
    - ms-vscode.cmake-tools
    - ms-vscode.copilot-mermaid-diagram
    - ms-vscode.remote-explorer
    - ms-vscode.remote-repositories
    - ms-vscode.remote-server
    - ms-vscode.test-adapter-converter
    - oderwat.indent-rainbow
    - pkief.material-icon-theme
    - redhat.ansible
    - redhat.vscode-xml
    - redhat.vscode-yaml
    - saoudrizwan.claude-dev
    - sumneko.lua
    - vscodevim.vim
