- name: Create the `aur_builder` user
  become: true
  ansible.builtin.user:
    name: aur_builder
    create_home: true
    group: wheel
- name: Allow the `aur_builder` user to run `sudo` without a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: true
    mode: 0644
    validate: 'visudo -cf %s'
- name: Install AUR packages
  kewlfft.aur.aur:
    name: '{{ item}}'
    state: present
    upgrade: true
    update_cache: true
    use: paru
  become: true
  become_user: aur_builder
  loop:
    - nushell
    - android-tools
    - anki-bin
    - tokei
    - luarocks
    - uv
    - ctop
    - termshark
    - dive
    - espanso-x11
    - firefox
    - ansible
    - act
    - bruno-bin
    - bore
    - ansible-lint
    - arandr
    - fx
    - evince
    - crush-bin
    - aria2
    - ark
    - atuin
    - base
    - base-devel
    - bash-completion
    - bat
    - calibre
    - catppuccin-cursors-mocha
    - chaotic-keyring
    - chaotic-mirrorlist
    - cheat
    - cmus
    - containerd
    - copyq
    - delve
    - dns-over-https
    - podman
    - dracula-gtk-theme
    - dunst
    - epapirus-icon-theme-git
    - epub-thumbnailer-git
    - eza
    - fd
    - feh
    - ffmpeg
    - ffmpeg-audio-thumbnailer
    - ffmpegthumbnailer
    - flameshot
    - fzf
    - ghostty
    - gimp
    - git
    - git-delta
    - github-cli
    - gitleaks
    - gnu-free-fonts
    - gnu-netcat
    - go
    - golangci-lint-bin
    - go-tools
    - go-yq
    - gpart
    - gparted
    - grub
    - grype-bin
    - gsound
    - hadolint-bin
    - heimdall
    - helm
    - htop
    - i3blocks
    - i3lock
    - i3status-rust
    - i3-wm
    - imagewriter
    - jq
    - jre-openjdk
    - k9s
    - keepassxc
    - keychain
    - keyd
    - kubectl
    - kustomize
    - localsend-bin
    - lua
    - lxappearance-gtk3
    - maestral-qt
    - mousepad
    - mpv
    - neovim
    - papirus-icon-theme
    - neovim-qt
    - nmap
    - nomacs
    - obsidian
    - oha
    - oh-my-posh-bin
    - paru
    - pavucontrol
    - picom-arian8j2-git
    - playerctl
    - pulseaudio
    - pulseaudio-alsa
    - qbittorrent
    - revive
    - ripgrep
    - ripgrep-all
    - sheldon
    - shellcheck
    - slack-desktop
    - sql-formatter
    - stow
    - tcpdump
    - terraform
    - tesseract
    - tesseract-data-eng
    - the_silver_searcher
    - thunar
    - thunar-archive-plugin-git
    - tmux
    - traceroute
    - ttf-font-awesome-5
    - ttf-jetbrains-mono-nerd
    - tumbler-devel
    - tumbler-extra-thumbnailers
    - ueberzugpp
    - rofi
    - unclutter
    - unrar
    - unzip
    - vhs
    - vi
    - vim
    - visual-studio-code-bin
    - wget
    - whois
    - xarchiver
    - xclip
    - yamlfmt
    - yazi
    - zathura
    - zathura-pdf-mupdf
    - zoxide
    - zsh
