- name: Change default shell to zsh
  ansible.builtin.user:
    name: '{{ user.name }}'
    shell: /bin/zsh
  become: true

- name: Stow dotfiles
  ansible.builtin.command: stow .
  args:
    chdir: '/home/{{ user.name }}/.dotfiles'
  become: true
  become_user: '{{ user.name }}'

- name: Copy keyd configuration file
  ansible.builtin.copy:
    src: /home/{{ user.name }}/.config/keyd/default.conf
    dest: /etc/keyd/default.conf
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Enable keyd service
  ansible.builtin.systemd:
    name: keyd
    enabled: true
  become: true

- name: Start keyd service
  ansible.builtin.systemd:
    name: keyd
    state: started
  become: true

- name: Reload keyd configuration
  ansible.builtin.command: keyd reload
  become: true